import type { EquipmentType, FaultCategory } from "./types";

export type MaterialSpec = {
  readonly code: string;
  readonly name: string;
  readonly unit: string;
  readonly price: number;
  readonly categories: readonly FaultCategory[];
  readonly fitsTypes?: readonly EquipmentType[];
};

export const MATERIAL_SPECS: readonly MaterialSpec[] = [
  {
    code: "BRG-22234",
    name: "Подшипник 22234 CC/W33",
    unit: "шт",
    price: 165_000,
    categories: ["mechanical"],
    fitsTypes: ["crusher", "mill"],
  },
  {
    code: "BRG-22320",
    name: "Подшипник 22320 CC/W33",
    unit: "шт",
    price: 96_000,
    categories: ["mechanical"],
    fitsTypes: ["screen", "feeder", "classifier", "other"],
  },
  {
    code: "BRG-6312",
    name: "Подшипник 6312 2RS",
    unit: "шт",
    price: 18_500,
    categories: ["mechanical"],
    fitsTypes: ["conveyor"],
  },
  {
    code: "BRG-6310",
    name: "Подшипник 6310 2RS",
    unit: "шт",
    price: 14_200,
    categories: ["mechanical"],
    fitsTypes: ["pump"],
  },
  {
    code: "BRG-6309",
    name: "Подшипник 6309 ZZ",
    unit: "шт",
    price: 9_800,
    categories: ["mechanical"],
    fitsTypes: ["fan", "compressor"],
  },
  {
    code: "ROLLER-159",
    name: "Ролик конвейерный Ø159×950",
    unit: "шт",
    price: 38_500,
    categories: ["mechanical"],
    fitsTypes: ["conveyor"],
  },
  {
    code: "BELT-1000",
    name: "Лента конвейерная ТК-200, ширина 1000",
    unit: "м",
    price: 41_000,
    categories: ["mechanical"],
    fitsTypes: ["conveyor"],
  },
  {
    code: "BELT-CLAMP",
    name: "Соединитель ленточный механический",
    unit: "компл",
    price: 7_200,
    categories: ["mechanical"],
    fitsTypes: ["conveyor"],
  },
  {
    code: "LINER-CRUSH",
    name: "Плита футеровочная дробилки",
    unit: "шт",
    price: 480_000,
    categories: ["mechanical"],
    fitsTypes: ["crusher"],
  },
  {
    code: "LINER-MILL",
    name: "Плита футеровочная мельницы",
    unit: "шт",
    price: 62_000,
    categories: ["mechanical"],
    fitsTypes: ["mill"],
  },
  {
    code: "SCREEN-DECK",
    name: "Панель грохота полиуретановая",
    unit: "шт",
    price: 54_000,
    categories: ["mechanical"],
    fitsTypes: ["screen"],
  },
  {
    code: "PKG-GLAND",
    name: "Набивка сальниковая графитовая Ø12",
    unit: "кг",
    price: 11_800,
    categories: ["mechanical"],
    fitsTypes: ["pump"],
  },
  {
    code: "SEAL-MECH",
    name: "Уплотнение торцевое насоса",
    unit: "шт",
    price: 134_000,
    categories: ["mechanical"],
    fitsTypes: ["pump"],
  },
  {
    code: "SLEEVE-SHAFT",
    name: "Втулка защитная вала",
    unit: "шт",
    price: 27_500,
    categories: ["mechanical"],
    fitsTypes: ["pump"],
  },
  {
    code: "SEAL-GASKET",
    name: "Паронит прокладочный ПМБ",
    unit: "кг",
    price: 4_300,
    categories: ["mechanical", "hydraulic"],
  },
  {
    code: "COUPLING-INS",
    name: "Вставка упругая муфты",
    unit: "шт",
    price: 9_400,
    categories: ["mechanical"],
  },
  {
    code: "GEAR-PINION",
    name: "Шестерня привода",
    unit: "шт",
    price: 185_000,
    categories: ["mechanical"],
    fitsTypes: ["crusher", "mill", "feeder", "classifier"],
  },
  {
    code: "BOLT-M24",
    name: "Болт М24×90 кл. 10.9 с гайкой",
    unit: "шт",
    price: 650,
    categories: ["mechanical"],
  },
  {
    code: "WELD-ROD",
    name: "Электроды УОНИ-13/55 Ø4",
    unit: "кг",
    price: 2_450,
    categories: ["mechanical"],
  },
  {
    code: "STEEL-PLATE",
    name: "Лист стальной Ст3 10 мм",
    unit: "кг",
    price: 780,
    categories: ["mechanical"],
  },
  { code: "CABLE-KG", name: "Кабель КГ 3×25", unit: "м", price: 4_800, categories: ["electrical"] },
  {
    code: "LUG-CABLE",
    name: "Наконечники кабельные медные",
    unit: "уп",
    price: 3_100,
    categories: ["electrical"],
  },
  {
    code: "CONTACTOR-25A",
    name: "Контактор 25 А",
    unit: "шт",
    price: 38_500,
    categories: ["electrical"],
  },
  {
    code: "FUSE-NH",
    name: "Предохранитель НН 100 А",
    unit: "шт",
    price: 3_400,
    categories: ["electrical"],
  },
  {
    code: "VARNISH-INS",
    name: "Лак электроизоляционный",
    unit: "л",
    price: 6_800,
    categories: ["electrical"],
  },
  {
    code: "WIRE-WINDING",
    name: "Провод обмоточный ПЭТ-155",
    unit: "кг",
    price: 5_600,
    categories: ["electrical"],
  },
  {
    code: "SENSOR-PT100",
    name: "Датчик температуры PT100",
    unit: "шт",
    price: 17_500,
    categories: ["electrical"],
  },
  {
    code: "SENSOR-VIB",
    name: "Датчик вибрации",
    unit: "шт",
    price: 43_000,
    categories: ["electrical"],
  },
  {
    code: "SENSOR-LEVEL",
    name: "Датчик уровня",
    unit: "шт",
    price: 48_000,
    categories: ["electrical", "lubrication"],
  },
  {
    code: "OIL-I40A",
    name: "Масло индустриальное И-40А",
    unit: "л",
    price: 1_350,
    categories: ["lubrication", "mechanical"],
  },
  {
    code: "OIL-TAD17",
    name: "Масло трансмиссионное ТАД-17и",
    unit: "л",
    price: 1_900,
    categories: ["lubrication", "mechanical"],
  },
  {
    code: "GREASE-LITOL",
    name: "Смазка Литол-24",
    unit: "кг",
    price: 2_300,
    categories: ["lubrication", "mechanical"],
  },
  {
    code: "GREASE-EP2",
    name: "Смазка пластичная EP-2",
    unit: "кг",
    price: 3_900,
    categories: ["lubrication"],
  },
  {
    code: "OIL-FILTER",
    name: "Фильтр масляный",
    unit: "шт",
    price: 12_400,
    categories: ["lubrication", "hydraulic"],
  },
  {
    code: "HYD-OIL",
    name: "Масло гидравлическое МГЕ-46В",
    unit: "л",
    price: 1_650,
    categories: ["hydraulic"],
  },
  {
    code: "HOSE-RVD",
    name: "Рукав высокого давления РВД",
    unit: "м",
    price: 8_800,
    categories: ["hydraulic"],
  },
  {
    code: "HYD-SEALKIT",
    name: "Ремкомплект гидроцилиндра",
    unit: "компл",
    price: 56_000,
    categories: ["hydraulic"],
  },
  {
    code: "AIR-HOSE",
    name: "Шланг пневматический Ø16",
    unit: "м",
    price: 1_900,
    categories: ["pneumatic"],
  },
  {
    code: "VALVE-52",
    name: "Пневмораспределитель 5/2",
    unit: "шт",
    price: 32_000,
    categories: ["pneumatic"],
  },
  {
    code: "AIR-FILTER",
    name: "Фильтр воздушный компрессора",
    unit: "шт",
    price: 8_500,
    categories: ["pneumatic", "mechanical"],
  },
];
