import { StyleSheet } from "@react-pdf/renderer";
import type { Tone } from "@/lib/reports/document";
import { REPORT_FONT_FAMILY } from "@/lib/reports/pdf/fonts";

export const PDF_COLORS = {
  text: "#0f1720",
  muted: "#4b5868",
  border: "#cfd6e0",
  stripe: "#f3f5f8",
  header: "#e6eaf0",
  accent: "#b45309",
  accentSoft: "#fdf1e2",
  good: "#15803d",
  bad: "#c81e1e",
  bar: "#d97706",
};

export const TONE_COLORS: Record<Tone, string> = {
  default: PDF_COLORS.text,
  good: PDF_COLORS.good,
  bad: PDF_COLORS.bad,
  accent: PDF_COLORS.accent,
};

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: REPORT_FONT_FAMILY,
    fontSize: 9,
    color: PDF_COLORS.text,
    paddingTop: 44,
    paddingBottom: 44,
    paddingHorizontal: 32,
    lineHeight: 1.35,
  },
  runningHeader: {
    position: "absolute",
    top: 18,
    left: 32,
    right: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: PDF_COLORS.muted,
    borderBottomWidth: 0.5,
    borderBottomColor: PDF_COLORS.border,
    paddingBottom: 3,
  },
  footer: {
    position: "absolute",
    bottom: 18,
    left: 32,
    right: 32,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: PDF_COLORS.muted,
    borderTopWidth: 0.5,
    borderTopColor: PDF_COLORS.border,
    paddingTop: 3,
  },
  brand: {
    fontSize: 8,
    fontWeight: 600,
    color: PDF_COLORS.accent,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  title: { fontSize: 18, fontWeight: 600, marginTop: 4, lineHeight: 1.25 },
  subtitle: { fontSize: 10, color: PDF_COLORS.muted, marginTop: 2, lineHeight: 1.3 },
  metaRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 8, gap: 4 },
  chip: {
    borderWidth: 0.5,
    borderColor: PDF_COLORS.border,
    borderRadius: 3,
    paddingHorizontal: 5,
    paddingVertical: 2,
    fontSize: 8,
  },
  chipLabel: { color: PDF_COLORS.muted },
  headerBlock: {
    borderBottomWidth: 2,
    borderBottomColor: PDF_COLORS.accent,
    paddingBottom: 8,
    marginBottom: 12,
  },
  kpiGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginBottom: 12 },
  kpi: {
    width: "23.8%",
    borderWidth: 1,
    borderColor: PDF_COLORS.border,
    borderRadius: 4,
    paddingHorizontal: 7,
    paddingVertical: 5,
  },
  kpiLabel: {
    fontSize: 7,
    color: PDF_COLORS.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  kpiValue: { fontSize: 14, fontWeight: 600, marginTop: 2, lineHeight: 1.25 },
  section: { marginBottom: 12 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    lineHeight: 1.3,
    marginBottom: 5,
    paddingLeft: 6,
    borderLeftWidth: 3,
    borderLeftColor: PDF_COLORS.accent,
  },
  table: { borderWidth: 0.5, borderColor: PDF_COLORS.border },
  row: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: PDF_COLORS.border,
  },
  rowStriped: { backgroundColor: PDF_COLORS.stripe },
  headRow: { backgroundColor: PDF_COLORS.header },
  totalsRow: { backgroundColor: PDF_COLORS.accentSoft },
  cell: { paddingHorizontal: 4, paddingVertical: 3, fontSize: 8 },
  headCell: { fontWeight: 600, fontSize: 7.5, color: PDF_COLORS.muted },
  boldCell: { fontWeight: 600 },
  right: { textAlign: "right" },
  empty: { color: PDF_COLORS.muted, fontSize: 8, paddingVertical: 4 },
  fields: { flexDirection: "row", flexWrap: "wrap" },
  field: { width: "50%", paddingVertical: 3, paddingRight: 8 },
  fieldWide: { width: "100%", paddingVertical: 3 },
  fieldLabel: { fontSize: 7, color: PDF_COLORS.muted, textTransform: "uppercase" },
  fieldValue: { fontSize: 9 },
  paragraph: { marginBottom: 4 },
  bulletRow: { flexDirection: "row", marginBottom: 2 },
  bullet: { width: 10, color: PDF_COLORS.accent },
  bulletText: { flex: 1 },
  note: { fontSize: 7, color: PDF_COLORS.muted, marginTop: 2 },
  barRow: { flexDirection: "row", alignItems: "center", marginBottom: 3 },
  barLabel: { width: "34%", fontSize: 8, paddingRight: 6 },
  barTrack: { flex: 1, height: 9, backgroundColor: PDF_COLORS.stripe },
  barFill: { height: 9, backgroundColor: PDF_COLORS.bar },
  barValue: { width: 64, fontSize: 8, textAlign: "right" },
});
